import type { FieldRaw, FieldMeta } from "@directus/types";

type FieldMetaExtend = Omit<FieldMeta, 'id'> & {id?: number};

interface FieldRawExtend extends Omit<FieldRaw, "meta"> {
    meta: FieldMetaExtend;
}

export const FIELD_IMG_HASH: FieldRawExtend = {
  collection: "directus_files",
  field: "blur_img_hash",
  type: "string",
  meta: {
    collection: "directus_files",
    field: "blur_img_hash",
    special: null,
    interface: "input",
    options: null,
    display: null,
    display_options: null,
    readonly: true,
    hidden: false,
    sort: 1,
    width: "full",
    translations: null,
    note: "Generated by the Blur Image Generator extension",
    conditions: null,
    required: false,
    system: true,
    group: null,
    validation: null,
    validation_message: null,
  },
  schema: {
    name: "blur_img_hash",
    table: "directus_files",
    data_type: "varchar",
    default_value: null,
    max_length: 255,
    numeric_precision: null,
    numeric_scale: null,
    is_indexed: false,
    is_generated: false,
    generation_expression: null,
    is_nullable: true,
    is_unique: false,
    is_primary_key: false,
    has_auto_increment: false,
    foreign_key_column: null,
    foreign_key_table: null,
  },
};

export const FIELD_HASH_ALGORITHM: FieldRawExtend = {
  collection: "directus_settings",
  field: "blur_image_generator",
  type: "string",
  meta: {
    collection: "directus_settings",
    field: "blur_image_generator",
    special: null,
    interface: "select-dropdown",
    options: {
      choices: [
        {
          text: "Thumbhash",
          value: "thumbhash"
        },
        {
          text: "Blurhash",
          value: "blurhash"
        }
      ]
    },
    display: "formatted-value",
    display_options: null,
    readonly: false,
    hidden: false,
    sort: 1,
    width: "full",
    translations: null,
    note: "Select the hash algorithm to use for generating blur image placeholders. The default is Thumbhash. <br> <br> <b>Note:</b> If you change the algorithm, you need to regenerate all the hashes for the images.",
    conditions: null,
    required: false,
    group: null,
    validation: null,
    validation_message: null,
  },
  schema: {
    name: "blur_image_generator",
    table: "directus_settings",
    data_type: "varchar",
    default_value: "thumbhash",
    max_length: 255,
    numeric_precision: null,
    numeric_scale: null,
    is_indexed: false,
    is_generated: false,
    generation_expression: null,
    is_nullable: true,
    is_unique: false,
    is_primary_key: false,
    has_auto_increment: false,
    foreign_key_column: null,
    foreign_key_table: null,
  },
};

const FIELDS_TO_ADD = [FIELD_IMG_HASH];

export { FIELDS_TO_ADD };
