name: Merge main to develop
permissions:
  contents: write # for checkout

on: 
  workflow_run:
    workflows: "Release"
    types: [completed]
    branches: [main]

jobs:
  merge-main-back-to-develop:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge main back to develop
      run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff main -m "Auto-merge main back to develop"
          git push